function keypoints = get_keypoints(in1,in2)
%GET_KEYPOINTS
%    KEYPOINTS = GET_KEYPOINTS(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    29-Oct-2021 15:25:00

l1 = in2(5,:);
l2 = in2(6,:);
th1 = in1(1,:);
th2 = in1(2,:);
t2 = cos(th1);
t3 = sin(th1);
t4 = th1+th2;
t5 = l1.*t2;
t6 = l1.*t3;
t7 = -t5;
keypoints = [t6;t7;0.0;t6+l2.*sin(t4);t7-l2.*cos(t4);0.0];
