function E = total_e(in1,in2,in3)
%TOTAL_E
%    E = TOTAL_E(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    29-Oct-2021 15:25:00

I1 = in3(3,:);
I2 = in3(4,:);
c1 = in3(7,:);
c2 = in3(8,:);
dth1 = in1(3,:);
dth2 = in1(4,:);
g = in3(17,:);
k1 = in3(9,:);
k2 = in3(10,:);
k3 = in3(11,:);
l1 = in3(5,:);
l2 = in3(6,:);
l_0 = in3(14,:);
m1 = in3(1,:);
m2 = in3(2,:);
rx = in3(15,:);
ry = in3(16,:);
th1 = in1(1,:);
th2 = in1(2,:);
th1_0 = in3(12,:);
th2_0 = in3(13,:);
t2 = cos(th1);
t3 = sin(th1);
t4 = th1+th2;
t5 = c1.^2;
t6 = dth1.^2;
t7 = l1.*t2;
t8 = cos(t4);
t9 = l1.*t3;
t10 = sin(t4);
t11 = c2.*t8;
t12 = t7+t11;
E = (I1.*t6)./2.0+(I2.*(dth1+dth2).^2)./2.0+(m1.*(t2.^2.*t5.*t6+t3.^2.*t5.*t6))./2.0+(m2.*((dth1.*(t9+c2.*t10)+c2.*dth2.*t10).^2+(dth1.*t12+dth2.*t11).^2))./2.0+(k1.*(th1-th1_0).^2)./2.0+(k2.*(th2-th2_0).^2)./2.0+(k3.*(l_0-sqrt(abs(ry+t7+l2.*t8).^2+abs(-rx+t9+l2.*t10).^2)).^2)./2.0-g.*m2.*t12-c1.*g.*m1.*t2;
